import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { apiFetch } from '../../lib/apiClient';
import type { PlanCard,PlanCreatePayload,PlanDetail,PlanningOptions } from '../../features/planning/types';
interface R<T>{success:boolean;message:string;data:T}
export const planningKeys={options:['planning','options'] as const,list:(q:string)=>['planning','list',q] as const,detail:(id:string)=>['planning','detail',id] as const};
export function usePlanningOptions(){return useQuery({queryKey:planningKeys.options,queryFn:async()=>(await apiFetch<R<PlanningOptions>>('/api/planning/options')).data})}
export function usePlans(params:URLSearchParams){const q=params.toString();return useQuery({queryKey:planningKeys.list(q),queryFn:async()=>(await apiFetch<R<PlanCard[]>>(`/api/planning${q?`?${q}`:''}`)).data})}
export function usePlan(id:string){return useQuery({queryKey:planningKeys.detail(id),queryFn:async()=>(await apiFetch<R<PlanDetail>>(`/api/planning/${id}`)).data,enabled:Boolean(id)})}
export function useCreatePlan(){const c=useQueryClient();return useMutation({mutationFn:async(p:PlanCreatePayload)=>(await apiFetch<R<PlanDetail>>('/api/planning',{method:'POST',body:JSON.stringify(p)})).data,retry:0,onSuccess:()=>c.invalidateQueries({queryKey:['planning']})})}
export function useUpdatePlan(){const c=useQueryClient();return useMutation({mutationFn:async({id,payload}:{id:string;payload:Record<string,unknown>})=>(await apiFetch<R<PlanDetail>>(`/api/planning/${id}`,{method:'PUT',body:JSON.stringify(payload)})).data,onSuccess:d=>{c.setQueryData(planningKeys.detail(d.id),d);c.invalidateQueries({queryKey:['planning','list']})}})}
export function useDeletePlan(){const c=useQueryClient();return useMutation({mutationFn:async(id:string)=>(await apiFetch<R<{id:string;name:string}>>(`/api/planning/${id}`,{method:'DELETE'})).data,onSuccess:d=>{c.setQueriesData<PlanCard[]>({queryKey:['planning','list']},old=>old?.filter(plan=>plan.id!==d.id));c.removeQueries({queryKey:planningKeys.detail(d.id)});c.invalidateQueries({queryKey:['planning','list']})}})}
export function useCreateMilestone(){const c=useQueryClient();return useMutation({mutationFn:async({planId,payload}:{planId:string;payload:Record<string,unknown>})=>(await apiFetch<R<PlanDetail>>(`/api/planning/${planId}/milestones`,{method:'POST',body:JSON.stringify(payload)})).data,onSuccess:d=>{c.setQueryData(planningKeys.detail(d.id),d);c.invalidateQueries({queryKey:['planning','list']})}})}
export function useUpdateMilestone(){const c=useQueryClient();return useMutation({mutationFn:async({planId,milestoneId,payload}:{planId:string;milestoneId:string;payload:Record<string,unknown>})=>(await apiFetch<R<PlanDetail>>(`/api/planning/${planId}/milestones/${milestoneId}`,{method:'PUT',body:JSON.stringify(payload)})).data,onSuccess:d=>{c.setQueryData(planningKeys.detail(d.id),d);c.invalidateQueries({queryKey:['planning','list']})}})}
export function useDeleteMilestone(){const c=useQueryClient();return useMutation({mutationFn:async({planId,milestoneId}:{planId:string;milestoneId:string})=>(await apiFetch<R<PlanDetail>>(`/api/planning/${planId}/milestones/${milestoneId}`,{method:'DELETE'})).data,onSuccess:d=>{c.setQueryData(planningKeys.detail(d.id),d);c.invalidateQueries({queryKey:['planning','list']})}})}
export function useUpdatePlanItem(){const c=useQueryClient();return useMutation({mutationFn:async({planId,kind,itemId,payload}:{planId:string;kind:string;itemId:string;payload:Record<string,unknown>})=>(await apiFetch<R<PlanDetail>>(`/api/planning/${planId}/${kind}/${itemId}`,{method:'PATCH',body:JSON.stringify(payload)})).data,onSuccess:d=>{c.setQueryData(planningKeys.detail(d.id),d);c.invalidateQueries({queryKey:['planning','list']})}})}
export function useAddPlanNote(){const c=useQueryClient();return useMutation({mutationFn:async({id,text}:{id:string;text:string})=>(await apiFetch<R<PlanDetail>>(`/api/planning/${id}/notes`,{method:'POST',body:JSON.stringify({text})})).data,onSuccess:d=>c.setQueryData(planningKeys.detail(d.id),d)})}
