import { AlertCircle, CheckCircle2, Download, FileText, Loader2, ShieldCheck } from 'lucide-react';
import { useGenerateStoryPdf, useValidateStoryDraft } from '../../../hooks/api/useReports';
import { useReportBuilderStore } from '../../../store/reportBuilderStore';

export default function Step5Export() {
  const store = useReportBuilderStore();
  const validate = useValidateStoryDraft();
  const generate = useGenerateStoryPdf();
  const runValidation = () => store.draftId && validate.mutate(store.draftId);
  const exportPdf = () => store.draftId && generate.mutate({ id: store.draftId, expectedVersion: store.draftVersion });
  return <div className="mx-auto max-w-3xl px-6 py-10"><div className="mb-8 text-center"><h2 className="text-2xl font-extrabold text-slate-900 dark:text-white">Export Presentation PDF</h2><p className="mt-2 text-sm text-[var(--text-muted)]">Professional 16:9 vector PDF. One report page per presentation page, backed by an immutable snapshot.</p></div><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900"><div className="flex gap-4 border-b border-slate-200 bg-slate-50 p-6 dark:border-slate-700 dark:bg-slate-800"><span className="grid h-12 w-12 place-items-center rounded-xl bg-[var(--sgh-cyan-primary,#00A3E0)]/10 text-[var(--sgh-cyan-primary,#00A3E0)]"><FileText /></span><div><h3 className="text-lg font-extrabold text-slate-900 dark:text-white">{store.configuration.report_name}</h3><p className="mt-1 text-sm text-[var(--text-muted)]">{store.configuration.start_month} {store.configuration.start_year} vs {store.configuration.end_month} {store.configuration.end_year} - {store.slides.length} pages</p></div></div><div className="p-7">
      {!validate.data && !generate.data && <div className="text-center"><ShieldCheck className="mx-auto mb-4 text-[var(--sgh-cyan-primary,#00A3E0)]" size={40} /><p className="mb-6 text-sm leading-6 text-slate-600 dark:text-slate-300">Run server validation to check scope, periods, page data, targets, action owners, action due dates, and missing configuration.</p><button onClick={runValidation} disabled={!store.draftId || store.saveState !== 'saved' || validate.isPending} className="rounded-xl bg-[var(--sgh-cyan-primary,#00A3E0)] px-7 py-3 font-extrabold text-white transition hover:bg-[var(--sgh-cyan-dark,#0084CE)] disabled:opacity-50">{validate.isPending ? <Loader2 className="inline animate-spin" /> : 'Validate for export'}</button></div>}
      {validate.error && <div className="flex gap-3 rounded-xl border border-red-200 bg-red-50 p-4 text-red-700 dark:border-red-900/50 dark:bg-red-950/30 dark:text-red-300"><AlertCircle />{validate.error.message}</div>}
      {validate.data && !generate.data && <div><div className={`mb-5 flex gap-3 rounded-xl border p-4 ${validate.data.valid ? 'border-emerald-200 bg-emerald-50 text-emerald-800 dark:border-emerald-900/50 dark:bg-emerald-950/30 dark:text-emerald-200' : 'border-red-200 bg-red-50 text-red-800 dark:border-red-900/50 dark:bg-red-950/30 dark:text-red-200'}`}>{validate.data.valid ? <CheckCircle2 className="text-emerald-600 dark:text-emerald-400" /> : <AlertCircle className="text-red-600 dark:text-red-400" />}<div><b>{validate.data.valid ? 'Validation passed' : 'Validation errors found'}</b><p className="mt-1 text-sm">{validate.data.issues.length} error(s) and warning(s) reported.</p></div></div>{validate.data.valid && <button onClick={exportPdf} disabled={generate.isPending} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[var(--sgh-cyan-primary,#00A3E0)] py-3 font-extrabold text-white hover:bg-[var(--sgh-cyan-dark,#0084CE)] disabled:opacity-50">{generate.isPending ? <Loader2 className="animate-spin" /> : <FileText />} Generate Presentation PDF</button>}</div>}
      {generate.error && <div className="mt-5 flex gap-3 rounded-xl border border-red-200 bg-red-50 p-4 text-red-700 dark:border-red-900/50 dark:bg-red-950/30 dark:text-red-300"><AlertCircle />{generate.error.message}</div>}
      {generate.data && <div className="text-center"><span className="mx-auto mb-4 grid h-16 w-16 place-items-center rounded-full bg-emerald-100 text-emerald-600 dark:bg-emerald-950/50 dark:text-emerald-400"><CheckCircle2 size={32} /></span><h3 className="text-xl font-extrabold text-slate-900 dark:text-white">Immutable PDF generated</h3><p className="mt-2 text-sm text-[var(--text-muted)]">Integrity ID: <code className="rounded bg-[var(--bg-sunken)] px-1.5 py-0.5 font-mono text-xs">{generate.data.integrity_identifier.slice(0, 16)}...</code></p><a href={generate.data.download_url} target="_blank" rel="noreferrer" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-7 py-3 font-extrabold text-white hover:bg-emerald-700"><Download /> Download PDF</a></div>}
    </div></div></div>;
}
